/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package GrafoBD;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-07-27")
public class ArestaNotFound extends org.apache.thrift.TException implements org.apache.thrift.TBase<ArestaNotFound, ArestaNotFound._Fields>, java.io.Serializable, Cloneable, Comparable<ArestaNotFound> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ArestaNotFound");

  private static final org.apache.thrift.protocol.TField ERROR_MSG_ARESTA_FIELD_DESC = new org.apache.thrift.protocol.TField("errorMsgAresta", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ArestaNotFoundStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ArestaNotFoundTupleSchemeFactory();

  public java.lang.String errorMsgAresta; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ERROR_MSG_ARESTA((short)1, "errorMsgAresta");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ERROR_MSG_ARESTA
          return ERROR_MSG_ARESTA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ERROR_MSG_ARESTA, new org.apache.thrift.meta_data.FieldMetaData("errorMsgAresta", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ArestaNotFound.class, metaDataMap);
  }

  public ArestaNotFound() {
  }

  public ArestaNotFound(
    java.lang.String errorMsgAresta)
  {
    this();
    this.errorMsgAresta = errorMsgAresta;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ArestaNotFound(ArestaNotFound other) {
    if (other.isSetErrorMsgAresta()) {
      this.errorMsgAresta = other.errorMsgAresta;
    }
  }

  public ArestaNotFound deepCopy() {
    return new ArestaNotFound(this);
  }

  @Override
  public void clear() {
    this.errorMsgAresta = null;
  }

  public java.lang.String getErrorMsgAresta() {
    return this.errorMsgAresta;
  }

  public ArestaNotFound setErrorMsgAresta(java.lang.String errorMsgAresta) {
    this.errorMsgAresta = errorMsgAresta;
    return this;
  }

  public void unsetErrorMsgAresta() {
    this.errorMsgAresta = null;
  }

  /** Returns true if field errorMsgAresta is set (has been assigned a value) and false otherwise */
  public boolean isSetErrorMsgAresta() {
    return this.errorMsgAresta != null;
  }

  public void setErrorMsgArestaIsSet(boolean value) {
    if (!value) {
      this.errorMsgAresta = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ERROR_MSG_ARESTA:
      if (value == null) {
        unsetErrorMsgAresta();
      } else {
        setErrorMsgAresta((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ERROR_MSG_ARESTA:
      return getErrorMsgAresta();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ERROR_MSG_ARESTA:
      return isSetErrorMsgAresta();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof ArestaNotFound)
      return this.equals((ArestaNotFound)that);
    return false;
  }

  public boolean equals(ArestaNotFound that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_errorMsgAresta = true && this.isSetErrorMsgAresta();
    boolean that_present_errorMsgAresta = true && that.isSetErrorMsgAresta();
    if (this_present_errorMsgAresta || that_present_errorMsgAresta) {
      if (!(this_present_errorMsgAresta && that_present_errorMsgAresta))
        return false;
      if (!this.errorMsgAresta.equals(that.errorMsgAresta))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetErrorMsgAresta()) ? 131071 : 524287);
    if (isSetErrorMsgAresta())
      hashCode = hashCode * 8191 + errorMsgAresta.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ArestaNotFound other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetErrorMsgAresta()).compareTo(other.isSetErrorMsgAresta());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetErrorMsgAresta()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.errorMsgAresta, other.errorMsgAresta);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ArestaNotFound(");
    boolean first = true;

    sb.append("errorMsgAresta:");
    if (this.errorMsgAresta == null) {
      sb.append("null");
    } else {
      sb.append(this.errorMsgAresta);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ArestaNotFoundStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ArestaNotFoundStandardScheme getScheme() {
      return new ArestaNotFoundStandardScheme();
    }
  }

  private static class ArestaNotFoundStandardScheme extends org.apache.thrift.scheme.StandardScheme<ArestaNotFound> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ArestaNotFound struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ERROR_MSG_ARESTA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.errorMsgAresta = iprot.readString();
              struct.setErrorMsgArestaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ArestaNotFound struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.errorMsgAresta != null) {
        oprot.writeFieldBegin(ERROR_MSG_ARESTA_FIELD_DESC);
        oprot.writeString(struct.errorMsgAresta);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ArestaNotFoundTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ArestaNotFoundTupleScheme getScheme() {
      return new ArestaNotFoundTupleScheme();
    }
  }

  private static class ArestaNotFoundTupleScheme extends org.apache.thrift.scheme.TupleScheme<ArestaNotFound> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ArestaNotFound struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetErrorMsgAresta()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetErrorMsgAresta()) {
        oprot.writeString(struct.errorMsgAresta);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ArestaNotFound struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.errorMsgAresta = iprot.readString();
        struct.setErrorMsgArestaIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

